"""initial schema: users, devices, readings (+ timescaledb hypertable)

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-12

Hand-written rather than autogenerated. Autogenerate cannot see the TimescaleDB
extension, cannot emit `create_hypertable`, and gets enum-type creation ordering
wrong, so the pieces that make this a *time-series* schema have to be authored by
hand. The table/constraint/index names below are spelled explicitly so they match
the names our naming convention produces on the models — otherwise a later
autogenerate run would see phantom renames.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The device_type enum, referenced by the devices.type column. `create_type=False`
# stops SQLAlchemy from auto-emitting CREATE TYPE inside create_table — we create
# and drop the type ourselves (below) so the ordering is explicit and offline
# `--sql` rendering never needs a live connection to check existence.
DEVICE_TYPE = postgresql.ENUM(
    "temperature",
    "pressure",
    "flow",
    name="device_type",
    create_type=False,
)


def upgrade() -> None:
    # TimescaleDB must be present before we can turn readings into a hypertable.
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    # Create the enum type once, up front.
    op.execute("CREATE TYPE device_type AS ENUM ('temperature', 'pressure', 'flow')")

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", DEVICE_TYPE, nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("min_threshold", sa.Float(), nullable=True),
        sa.Column("max_threshold", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_devices_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_devices"),
        sa.UniqueConstraint("user_id", "name", name="uq_devices_user_id_name"),
    )
    op.create_index("ix_devices_user_id", "devices", ["user_id"])

    op.create_table(
        "readings",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name="fk_readings_device_id_devices",
            ondelete="CASCADE",
        ),
        # Partition key `time` leads the composite PK — a hypertable requires its
        # partitioning column to be part of every unique/primary key.
        sa.PrimaryKeyConstraint("time", "device_id", name="pk_readings"),
    )
    # Convert readings into a hypertable partitioned on `time`, one chunk per day.
    # `create_default_indexes => FALSE`: TimescaleDB would otherwise auto-create an
    # index on `time` that lives only in the database, never in our models — which
    # would make `alembic revision --autogenerate` perpetually want to drop it. Our
    # PK (time, device_id) already provides a time-leading btree, so that default
    # index is redundant anyway. Every index on this table stays declared in code.
    op.execute(
        "SELECT create_hypertable('readings', 'time', "
        "chunk_time_interval => INTERVAL '1 day', create_default_indexes => FALSE)"
    )
    # Hot path: filter by device, then range-scan by time.
    op.create_index("ix_readings_device_id_time", "readings", ["device_id", "time"])


def downgrade() -> None:
    op.drop_index("ix_readings_device_id_time", table_name="readings")
    op.drop_table("readings")
    op.drop_index("ix_devices_user_id", table_name="devices")
    op.drop_table("devices")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.execute("DROP TYPE device_type")
    # The timescaledb extension is intentionally left installed: it is a
    # database-wide object other schemas may depend on, so tearing down this
    # migration should not remove it.
