/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create an account and return a token, so the client is logged in at once.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email + password for a 24-hour access token.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Return the authenticated user. Useful for the frontend to rehydrate state.
         */
        get: operations["read_current_user_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Current User */
        post: operations["delete_current_user_auth_me_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description List the caller's devices. Never anyone else's.
         */
        get: operations["index_devices_get"];
        put?: never;
        /**
         * Create
         * @description Register a new device owned by the caller.
         */
        post: operations["create_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show
         * @description Fetch one device by id — 404 unless the caller owns it.
         */
        get: operations["show_devices__device_id__get"];
        put?: never;
        post?: never;
        /**
         * Destroy
         * @description Delete a device and, by cascade, all of its readings.
         */
        delete: operations["destroy_devices__device_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update
         * @description Update one of the caller's devices.
         */
        patch: operations["update_devices__device_id__patch"];
        trace?: never;
    };
    "/devices/{device_id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description Append a single reading. Omit `time` to stamp it now.
         */
        post: operations["create_devices__device_id__readings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/readings/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bulk
         * @description Backfill many readings in one statement.
         */
        post: operations["create_bulk_devices__device_id__readings_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description Raw readings for one device, newest first.
         */
        get: operations["index_readings_get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description Delete readings for one device, optionally within a time window.
         *
         *     Returns how many rows were deleted. The caller must own the device.
         */
        delete: operations["delete_readings_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate
         * @description Bucketed rollups (`avg|min|max|p95`) over `1h|1d|1w` windows.
         */
        get: operations["aggregate_readings_aggregate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readings/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alerts
         * @description Threshold breaches since a given instant, newest first.
         */
        get: operations["alerts_readings_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AggregateBucket
         * @description One row of `GET /readings/aggregate` → `{bucket, value}`.
         */
        AggregateBucket: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Value */
            value: number;
        };
        /**
         * AggregateFn
         * @description Rollup functions accepted by `GET /readings/aggregate`.
         * @enum {string}
         */
        AggregateFn: "avg" | "min" | "max" | "p95";
        /**
         * AggregateWindow
         * @description Bucket widths accepted by `GET /readings/aggregate`.
         * @enum {string}
         */
        AggregateWindow: "1h" | "1d" | "1w";
        /**
         * AlertResponse
         * @description A reading that breached one of its device's configured thresholds.
         *
         *     Alerts are *derived*, not stored: there is no alerts table. Each response is
         *     computed by comparing readings against the owning device's thresholds at
         *     query time, which means editing a threshold retroactively changes what
         *     counts as an alert.
         *
         *     Carries `device_name` and `unit` so the row is self-describing — the AI
         *     assistant is required to cite device names, and making it join that back
         *     itself would be wasted round-trips.
         */
        AlertResponse: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Device Name */
            device_name: string;
            /** Unit */
            unit: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Value */
            value: number;
            /**
             * Bound
             * @enum {string}
             */
            bound: "min" | "max";
            /** Threshold */
            threshold: number;
        };
        /**
         * BulkReadingCreate
         * @description One item of `POST /devices/{device_id}/readings/bulk`.
         *
         *     Unlike the single-reading body, `time` is REQUIRED here. Defaulting a whole
         *     batch to "now" would give every row the same timestamp, and since the
         *     primary key is (time, device_id) the batch would collide with itself — a
         *     confusing 409 for what looks like valid input. Bulk uploads are backfills;
         *     they know their timestamps.
         */
        BulkReadingCreate: {
            /** Value */
            value: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /**
         * BulkReadingsResponse
         * @description `POST /devices/{device_id}/readings/bulk` → `{count}`.
         */
        BulkReadingsResponse: {
            /** Count */
            count: number;
        };
        /**
         * Credentials
         * @description Shared body for signup and login: `{email, password}`.
         */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** DeleteAccountRequest */
        DeleteAccountRequest: {
            /** Password */
            password: string;
        };
        /**
         * DeleteReadingsResponse
         * @description `DELETE /readings` → `{count}`.
         */
        DeleteReadingsResponse: {
            /** Count */
            count: number;
        };
        /**
         * DeviceCreate
         * @description Body for `POST /devices`.
         */
        DeviceCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["DeviceType"];
            /** Unit */
            unit: string;
            /** Min Threshold */
            min_threshold?: number | null;
            /** Max Threshold */
            max_threshold?: number | null;
        };
        /**
         * DeviceResponse
         * @description Public view of a device.
         */
        DeviceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            type: components["schemas"]["DeviceType"];
            /** Unit */
            unit: string;
            /** Min Threshold */
            min_threshold: number | null;
            /** Max Threshold */
            max_threshold: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DeviceType
         * @description The kinds of sensor we support.
         *
         *     Subclassing `str` makes each member behave like its string value, so it
         *     serializes straight to JSON as "temperature" etc. and Pydantic accepts the
         *     raw string from request bodies. Member names are UPPER_SNAKE per our
         *     conventions; the lowercase *values* are what we persist and expose.
         * @enum {string}
         */
        DeviceType: "temperature" | "pressure" | "flow";
        /** DeviceUpdate */
        DeviceUpdate: {
            /** Name */
            name?: string | null;
            /** Min Threshold */
            min_threshold?: number | null;
            /** Max Threshold */
            max_threshold?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ReadingCreate
         * @description Body for `POST /devices/{device_id}/readings`.
         *
         *     `time` is optional: a live sensor posting "now" can omit it, while a
         *     backfill supplies the original instant.
         */
        ReadingCreate: {
            /** Value */
            value: number;
            /** Time */
            time?: string | null;
        };
        /**
         * ReadingResponse
         * @description A single stored reading.
         */
        ReadingResponse: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Value */
            value: number;
        };
        /**
         * TokenResponse
         * @description What signup and login return: `{access_token, token_type}`.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserResponse
         * @description Public view of a user: `{id, email, created_at}`. Never the hash.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    delete_current_user_auth_me_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
        };
    };
    create_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    destroy_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_devices__device_id__readings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bulk_devices__device_id__readings_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkReadingCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkReadingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_readings_get: {
        parameters: {
            query: {
                limit?: number;
                start?: string | null;
                end?: string | null;
                device_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_readings_delete: {
        parameters: {
            query: {
                start?: string | null;
                end?: string | null;
                device_id: string;
                /** @description If true, return how many rows would be deleted without actually deleting them. */
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteReadingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aggregate_readings_aggregate_get: {
        parameters: {
            query: {
                start?: string | null;
                end?: string | null;
                device_id: string;
                window: components["schemas"]["AggregateWindow"];
                fn: components["schemas"]["AggregateFn"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateBucket"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_readings_alerts_get: {
        parameters: {
            query: {
                limit?: number;
                since: string;
                device_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
