/**
 * Shared types, re-exported from the generated OpenAPI definitions.
 *
 * `api-types.ts` is generated by `npm run gen:api` and must never be edited by
 * hand — it is the backend's contract, not ours. Everything here is an alias so
 * components import a short name while still being bound to the generated
 * shape: if the API changes, `npm run gen:api` makes the break a type error
 * rather than a runtime surprise.
 */
import type { components } from './api-types'

type Schemas = components['schemas']

export type Device = Schemas['DeviceResponse']
export type DeviceCreate = Schemas['DeviceCreate']
export type DeviceUpdate = Schemas['DeviceUpdate']
export type DeviceType = Schemas['DeviceType']
export type Reading = Schemas['ReadingResponse']
export type AggregateBucket = Schemas['AggregateBucket']
export type AggregateWindow = Schemas['AggregateWindow']
export type AggregateFn = Schemas['AggregateFn']
export type Alert = Schemas['AlertResponse']
export type User = Schemas['UserResponse']
export type Credentials = Schemas['Credentials']
export type TokenResponse = Schemas['TokenResponse']

/** The device types the API accepts, for building selects without duplication. */
export const DEVICE_TYPES = ['temperature', 'pressure', 'flow'] as const satisfies
  readonly DeviceType[]

/** Default unit suggestions per device type — a UI nicety, not an API rule. */
export const UNIT_BY_TYPE: Record<DeviceType, string> = {
  temperature: '°C',
  pressure: 'kPa',
  flow: 'L/min',
}
